### ISSUE TITLE
Reporting: sorting problem

### ISSUE THREAD

**Issue by annickvdp** [chamilo/chamilo-lms#1684]
### Current behavior / Resultado actual / Résultat actuel
When sorting userlist on firstname, it will sort on lastname and vice versa

### Expected behavior / Resultado esperado / Résultat attendu
When sorting userlist on firstname, it shoul sort on firstname

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
tested on https://campus.chamilo.org/

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11?

**Comment by ywarnier** [comment]
I believe this has been fixed. https://campus.chamilo.org/ is still in 1.10.8. Please test on https://1.11.chamilo.org/ (login as admin/admin if you like)

**Comment by annickvdp** [comment]
OK, thanks

**Comment by ywarnier** [comment]
This is likely to be related to #1653, and this one has been fixed.

**Comment by annickvdp** [comment]
@ywarnier: This problem is back when I tested on 11.chamilo.org

**Comment by annickvdp** [comment]
Maybe it's related to the language? I changed it for Dutch in earlier and current version like this: https://github.com/annickvdp/Chamilo-CVO-VOLT-2015/commit/c087b2860f6d63f1e16165a78084cf17ca1882ba
But I'm not sure if it will cause problems in other areas.

**Comment by jmontoyaa** [comment]
The default value for Dutch in Chamilo is:

`'dutch' =>            array('format' => 'title first_name last_name',  'sort_by' => 'first_name'),`

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/inc/lib/internationalization_database/name_order_conventions.php#L38

You can edit this setting only for your portal in

app/config/configuration.php

```
// Custom name_order_conventions
$_configuration['name_order_conventions'] = array(
 'dutch' => array('format' => 'title last_name first_name', 'sort_by' => 'last_name')
);
```
