### ISSUE TITLE
Cannot create new folder in filemanager

### ISSUE THREAD

**Issue by annickvdp** [chamilo/chamilo-lms#2221]
### Current behavior / Resultado actual / Résultat actuel
After typing folder name, the message "unable to create folder ..." displays
### Expected behavior / Resultado esperado / Résultat attendu
The folder gets created
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
insert an image in any textbox (for instance the introduction text on hoomepage of a course) > browse for a file > create a new folder in the filemanager (in case you want to upload an image in a new folder)
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4 (tested on localhost and https://11.chamilo.org/)

**Comment by ywarnier** [comment]
This should now be fixed on https://11.chamilo.org.
I cannot find the related issue anymore, but there's one in here that was referencing the same problem.
I'll let you test, and if I don't have an answer from you @annickvdp in a few days, I'll just consider this fixed.

**Comment by annickvdp** [comment]
Yes, it's fixed and it's probably this fix: https://github.com/chamilo/chamilo-lms/issues/2231
Sorry to have reported this again, I do try to search reported bugs first.

**Comment by annickvdp** [comment]
It's not completely solved: the folder "Test" I created using the editor, does not show up in the list of "documents", but is listed in the dropdown menu.

![image](https://user-images.githubusercontent.com/15210140/33609623-239a9084-d9c9-11e7-8208-9ca86dcfa1b0.png)

**Comment by ywarnier** [comment]
Mmmm... good point. @jmontoyaa could you make it so it creates the folder properly in c_document and c_item_property?

**Comment by bassuma** [comment]
Hi.
The patch worked for me.
In both cases.
The created folder appears in documents.

![ok](https://user-images.githubusercontent.com/25286516/33627007-5de7bf04-d9e3-11e7-83b6-fda2cf792676.PNG)

Thank you

**Comment by annickvdp** [comment]
@bassuma : your printscreen shows that the folder "test" shows in the dropdownlist in documents, but this it also show in the main folder without using the dropdown? That's where the problem is for me, can you check?

**Comment by jmontoyaa** [comment]
It works for me. You should create a new course and try again.
Or maybe try in https://11.chamilo.org/ (admin/admin)

**Comment by annickvdp** [comment]
You are corrrect. It works on https://11.chamilo.org/, but not on localhost. I'll have to figure out why.

**Comment by bassuma** [comment]
Hi @annickvdp.
The version I'm testing from chamilo is 1.11.6.
If you are using version 1.11.4 and used pacth # 2231.
Sometimes it works others do not.
When they launch the official version of chamilo 1.11.6.
This problem will be corrected.
I hope I contributed.
Thank you
