### ISSUE TITLE
"forum groups" hide threads in "general" forums

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#2269]
### Current behavior / Resultado actual / Résultat actuel

As a teacher, i create groups and forums associated to these groups. The "forum groups" appears in the "Forum" module, with other general forums.

From the "forum module", when i open a group forum (private or public)  and then i go back to the list of forums, there is an issue with "non groups forums" : when i open one of them, no threads are displayed. A refresh (F5) doesn't change anything. I don't have to open any thread in the group forum to generate this behavior.

I have to exit from the course to have the possibility to see the threads into the "non groups forums".

Reproduced when i connect as a student.

### Expected behavior / Resultado esperado / Résultat attendu
When i navigate from "groups forums" to "non groups forums" it should be possible to see the threads associated.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1..11.2 and 1.11.4
Reproduced here in a course (anatomy) : https://11.chamilo.org/

**Comment by ywarnier** [comment]
@tanchon please test on 11.chamilo.org. This will be considered fixed in 12h if no confirmation is received from your part. From our end it now works (with the fix provided).

**Comment by tanchon** [comment]
I made tests here : https://11.chamilo.org/courses/COMPTABILITEFINANCIERE/index.php

There is still the same issue in the "forum tool" : if i go in "forum groups" and then in "general forum", i cannot see the threads into "general forum". If i exit from the course and enter it is ok if i never go into the forum groups...

**Comment by NicoDucou** [comment]
I can not reproduce the problem.
I enter in the forum tool here : https://11.chamilo.org/main/forum/index.php?cidReq=COMPTABILITEFINANCIERE&id_session=0&gidReq=0&gradebook=0&origin=

I click on the name "Group forums" and get to the page https://11.chamilo.org/main/forum/viewforumcategory.php?cidReq=COMPTABILITEFINANCIERE&id_session=0&gidReq=0&gradebook=0&origin=&forumcategory=64

I click now on the blue arrow (the icon on the left of the action's icons) to got back to forum overview and get to this page : https://11.chamilo.org/main/forum/index.php?cidReq=COMPTABILITEFINANCIERE&id_session=0&gidReq=0&gradebook=0&origin=

I can see the general forum and the group forum.

Please indicate how to reproduce the problem please.

**Comment by tanchon** [comment]
I try to give you more informations.

I enter in the forum tool
I click on one of rhe forum groups (not on the name "group forums") : for example "group 0001". I can see the thread into this "group0001 forum".

From here, i dont't click on the blue arrow because i don't want to go into the "groups". I want to see the list of forums : so i click on the forum icon (the icon on the side of the screen or on the top of the screen).

The list of forum groups and general forum is displayed : then, i click on one of the general forum (for example : "forum général test".  No threads are listed.

It seems that there is a problem with the breadcrumb (see the file).
![forum chamilo](https://user-images.githubusercontent.com/24507698/35095710-cbb305a6-fc49-11e7-9edb-d970a77c0d9f.jpg)

**Comment by ywarnier** [comment]
We won't be able to fix this one in 1.11.6, sorry about that.

**Comment by ywarnier** [comment]
A workaround has been provided and fixing the real issue would probably be overkill considering this situation might happen to only one in every 10.000 users of the forum or so. Closing.
