### ISSUE TITLE
MP4 video not starting in chrome

### ISSUE THREAD

**Issue by xam1234** [chamilo/chamilo-lms#2493]
### Current behavior / Resultado actual / Résultat actuel
SCORM added MP4 video is not starting in chrome browser (win10x64)
For example video starts when you add a second video and switch to it, when you go back the first video also starts working but without search.
In firefox it works fine.
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Chrome browser 65
Create scorm in chamilo ->add mp4 video -> start scorm

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6 php 7.2

**Comment by ywarnier** [comment]
When you say "Create scorm in chamilo", you mean create a Chamilo learning path, or you mean import a SCORM package into Chamilo?
There is a very important difference there for us.

**Comment by xam1234** [comment]
hi, I meant create a Chamilo learning path.
Import didn't work couse I had my old chamilo version 1.10.6.

**Comment by NicoDucou** [comment]
I tried to reproduce the problem here : https://11.chamilo.org/main/lp/lp_controller.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=291&isStudentView=true

And I have the same result in Chrome and Firefox, you have the video opened in the default video player defined in the navigator and if I click on the play button it start reading.

Can you indicate if the example above work for you or try to reproduce your problem on 11.chamilo.org to be able to understand it.

**Comment by xam1234** [comment]
It works ok on 11.chamilo.org, so maybe it was fixed after 1.11.6
I see that when i open scorm on my site I have a jplayer error.
![123](https://user-images.githubusercontent.com/32258255/39122220-8491d166-46f4-11e8-8d77-75073848205e.png)

**Comment by ywarnier** [comment]
Maybe it was fixed. I believe we did indeed make a few changes related to videos and jplayer in previous weeks (in 1.11.x after 1.11.6).
I will close this report for now because we cannot reproduce it, but if post-1.11.8 you find the same issue, please don't hesitate to re-open or open a new issue.
Thank you for the detailed reporting!

**Comment by accountpayment** [comment]
I think this issue is still valid. I'm not able to use video loaded on servers. Hence as an alternative, I'm requested to use videos loaded from youtube. It does not sound professional for me as anyone can access the course. Any guide will be helpful.

**Comment by lonesomewalker** [comment]
Can't reproduce.
Works flawlessly on campus.chamilo.org also on all our portals.
Just checked.
Chrome (latest), Firefox (latest), Microsoft Edge (latest)

Maybe your installation is somewhat broken?
