### ISSUE TITLE
Integrate LTI plugin

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#2741]
### Current behavior / Resultado actual / Résultat actuel
LTI is supported through a plugin

### Expected behavior / Resultado esperado / Résultat attendu
LTI integrated in Chamilo v2

### Chamilo Version / Versión de Chamilo / Version de Chamilo
`master` branch

**Comment by AngelFQC** [comment]
Commits and cherry-picks done from 1.11.x and integration for now:
ae9a229d
cdead227
1f67ea7e
b15c15fe
c30a655c
90bbbc42
e6fa8e86
0f2522d2
17f55556
1ba2002e
637b56b3
e7cd164e

**Comment by ywarnier** [comment]
DB/Code structure ready for alpha 3.

**Comment by ywarnier** [comment]
Not working yet. Will fix after Beta.

**Comment by christianbeeznest** [comment]
Implemented and refined the LTI integration in Chamilo 2 core for both IMS/LTI Client and LTI Provider.

**Main updates:**

- improved client and provider administration flows

- aligned LTI 1.3 registration and launch parameters

- fixed legacy issues from the previous plugin-based model

- improved external tool assignment, edition, deletion, and launch behavior

- added the required DB change to support shared LTI resources across multiple courses

**Required migration:**

php bin/console doctrine:migrations:execute Chamilo\CoreBundle\Migrations\Schema\V200\Version20260317184500

**After pulling the changes, run:**

composer install
php bin/console cache:clear

refs https://github.com/christianbeeznest/chamilo-lms/commit/3dd2c824c887223c53c686e8fba1dd01873711a3

**Comment by ywarnier** [comment]
I'm moving this issue to 3.0. Most of the work has been done to port LTI to 2.0, but it's still presented as a plugin, where it should now be a native setting to enable or not. This requires moving folders and renaming classes (and carefully checking the migration of current data is done harmlessly), so I'm moving it to the 3.0 goalpost.
