### ISSUE TITLE
Invalid date / Invalid date

### ISSUE THREAD

**Issue by kemoche** [chamilo/chamilo-lms#3441]
**Describe**
I desired to create accesses by user report by date

**To Reproduce**
1. Go to Reporting - on the top menu - this after login as an administrator
2. Click on the "Star" - Admin View -> Accesses by user overview (Beta)
3. Scroll down to Date range and select the range
4. Upon clicking Generate - the See error - Invalid date / Invalid date & Validate dates

**Expected behavior**

**Screenshots**
Attached are the screenshots for the errors - 
  date input error01
  date input error02

**Desktop (please complete the following information):**
 - Browser waterfox (firefox) version 2020.07.01 (64bit)

**Server
 -  - OS Linux CENTOS 7.8 64 bit
 - Version of Chamilo: -1.11.10
 - Version of PHP: 7.2

**Additional context**
![date input error01](https://user-images.githubusercontent.com/69464866/89882366-66585680-dbcf-11ea-86ff-b7218759f516.jpg)
![date input error02](https://user-images.githubusercontent.com/69464866/89882375-69534700-dbcf-11ea-917e-59a9d688bcd8.jpg)

**Comment by ywarnier** [comment]
This is very likely to not be an issue anymore in 1.11.12, which should be released either today or in the coming days. I recommend you update when it comes out (the update process is very easy).
![access](https://user-images.githubusercontent.com/609839/90001502-cca5ad80-dc91-11ea-8cb4-58b8d26dd59b.png)

This being said, this is all JS so if it continues in 1.11.12, it probably means something is wrong with some of the plugins or other things you might have modified in your Chamilo installation. JavaScript errors can be seen in the browser debug console.

**Comment by shabsshab** [comment]
Iam unable to set the time other than :00  and 30
If i manually type time, it wil chnage back to 00 or 30

My agenda will be like this  11:15 to 12:00 or 09:00  to 09:45
How can i add the time 45 and 15 into drop down list, 

https://prntscr.com/u0237t
https://prntscr.com/u0233l


Using 1.11.12 version

**Comment by ywarnier** [comment]
@shabsshab This is unrelated to the initial task, and this is not a bug but a support question, so I would suggest, for similar questions, to ask on the forum.
Maybe this can help you (place the block in app/config/configuration.php, uncomment it and set to your needs):
```
//Allows to add increment in minutes to the date range component timepicker, example: 5,10,30 minutes
//$_configuration['timepicker_increment'] = 5;
```
This and many other settings that have not yet been moved to the database can be found in main/install/configuration.dist.php

**Comment by kemoche** [comment]
Thanks - my concern is resolved in Chamilo 1.11.12.
Also I have tried to update but getting an error - version required in upto 1.10.8. 
How do I update manually?
_PS: the downloaded version 1.11.12 shows it version 1.11.10._

**Comment by ywarnier** [comment]
@kemoche 
Please follow the update manual in the documentation/installation_guide.html of any Chamilo installation.
The downloaded version 1.11.12 still shows version 1.11.10 because we have not yet officially announced 1.11.12.

**Comment by kemoche** [comment]
Thanks
I have updated as in /documentation/installation_guide.html#3._Upgrade and I get a blank page.
The vendor file failed to copy (move).
I have also the below error which I have found in the error logs.
______
[17-Aug-2020 15:43:17 UTC] PHP Fatal error:  Uncaught Error: Class 'HookConditionalLogin' not found in /home/kbsco/public_html/mic/main/auth/conditional_login/conditional_login.php:21
Stack trace:
#0 /home/kbsco/public_html/mic/main/inc/lib/conditional_login.class.php(20): include_once()
#1 /home/kbsco/public_html/mic/main/inc/local.inc.php(548): ConditionalLogin::check_conditions(Array)
#2 /home/kbsco/public_html/mic/main/inc/global.inc.php(558): require('/home/kbsco/pub...')
#3 /home/kbsco/public_html/mic/index.php(15): require_once('/home/kbsco/pub...')
#4 {main}
  thrown in /home/kbsco/public_html/mic/main/auth/conditional_login/conditional_login.php on line 21
[17-Aug-2020 15:44:13 UTC] PHP Fatal error:  Uncaught Error: Class 'HookConditionalLogin' not found in /home/kbsco/public_html/mic/main/auth/conditional_login/conditional_login.php:21
Stack trace:
#0 /home/kbsco/public_html/mic/main/inc/lib/conditional_login.class.php(20): include_once()
#1 /home/kbsco/public_html/mic/main/inc/local.inc.php(548): ConditionalLogin::check_conditions(Array)
#2 /home/kbsco/public_html/mic/main/inc/global.inc.php(558): require('/home/kbsco/pub...')
#3 /home/kbsco/public_html/mic/index.php(15): require_once('/home/kbsco/pub...')
#4 {main}
  thrown in /home/kbsco/public_html/mic/main/auth/conditional_login/conditional_login.php on line 21
_________

Kindly assist.
Cheers

**Comment by ywarnier** [comment]
@kemoche These errors seem to be linked to vendor/ not moving, indeed.
The "Class 'HookConditionalLogin' not found is usually related to the autoloader of classes, which requires files in vendor/composer/ to be updated.

**Comment by ywarnier** [comment]
Please open a new issue. This has nothing to do with invalid dates.

**Comment by shabsshab** [comment]
There is a bug for this 

//Allows to add increment in minutes to the date range component timepicker, example: 5,10,30 minutes
//$_configuration['timepicker_increment'] = 5;

IF we enable this while creating repeat event that increment is getting added in the time for every day  and causing wrong entry for repeat event

If we keep a value of 15 it will chnage the day itself for weekly repeat

**Comment by NicoDucou** [comment]
Hi @shabsshab 
Has indicated by Yannick, your question has nothing to do with this issue, and the issue is closed.
So please create a new issue to report your problem and put details to be able to reproduce it because we can not reproduce it with what you indicate here. You have to indicate in which tool we have to go and what we are supposed to do. There is a template when creating a new issue that you should follow to be able to give us all the information needed.
Best regards
