### ISSUE TITLE
Bug with Backup of a "Zone on image" question (backup of a course/Quiz)

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3538]
Hi,

**Describe**
When i make a backup of a course and i select a quiz that integrate a "Zone on image" question, and then i want to import this exercise in another course (on the same platform), the question is imported, but not the picture.

Chamilo 1.11.12
Reproduced with 11.chamilo.org : [see here (the 2nd question : mappemonde cliquable)](https://11.chamilo.org/main/exercise/admin.php?cidReq=COURSTANCHON&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=488)

**To Reproduce**
1. In a course, Go to the Backup tool => Create a backup => Select an exercise with ZOI question => export
2. Go to another course
3. Go to Backup tool => Import the zip file with the course_info.dat informations
4. When i go into the exercise with a ZOI question, the image disappeared.

**Screenshots**
The image we can see into the 1st course :
![Capture2](https://user-images.githubusercontent.com/24507698/94199782-a2165980-feb9-11ea-810c-d28298327458.JPG)

The same view from the 2nd course (destination of the backup) : the image is lost...
![Capture](https://user-images.githubusercontent.com/24507698/94199856-bfe3be80-feb9-11ea-844b-47cd7d110feb.JPG)

in the edit mode...
![Capture3](https://user-images.githubusercontent.com/24507698/94199888-cb36ea00-feb9-11ea-876e-9354308e3c27.JPG)

**Server
Chamilo 1.11.12 - Linux

**Additional context**
The image seems to be "forgotten" during the backup process.

Thanks

Tanchon

**Comment by tanchon** [comment]
Reproduced with 11.chamilo.org : [see here (the 2nd question : mappemonde cliquable)](https://11.chamilo.org/main/exercise/admin.php?cidReq=COURSTESTTANCHON3&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=461)

**Comment by ywarnier** [comment]
There are chances this issue is fixed by 2 recent commits (after the release of 1.11.12). Could you try the same procedure on https://11.chamilo.org/ and let us know if it works, please?

**Comment by tanchon** [comment]
I tried to do that from this course : https://11.chamilo.org/courses/COURSTANCHON/index.php
I create a quiz with Image zone : Quiz test WITH IMAGE ZONES.
 I made a backup of this quiz (backup / make a backup ... / select elements...)

I tried to import it to another course : https://11.chamilo.org/courses/TESTPROF/index.php (backup / import... / select element

**But the process fails as you can see in this video** : https://youtu.be/iDN12XmLB6Q
Here is the backup file : [https://www.swisstransfer.com/d/a6df0fac-e5df-4f30-9fef-9a64326e2155](https://www.swisstransfer.com/d/a6df0fac-e5df-4f30-9fef-9a64326e2155)
 (it seems to to huge => almost 30 MO as there is only one exercise with 3 questions !)


If i export an exercise from my platform, the import process is ok (the size of the backup file is only 10 ko)... but the image in the question isn't displayed. Here is the backup file : https://www.swisstransfer.com/d/1a88fe96-3a91-4d34-a6db-2ff7e3d41d12

**Comment by ywarnier** [comment]
We won't be able to fix this in 1.11.14, sorry. Bumping to the next planned version (2.0).

**Comment by AngelFQC** [comment]
It seems like fixed now in 1.11.x branch

**Comment by tanchon** [comment]
H @AngelFQC 

I tried with 1.11.14 and i still have the issue when i follow these steps :

    In a course, Go to the Backup tool => Create a backup => Select an exercise with ZOI question => export
    Go to another course
    Go to Backup tool => Import the zip file with the course_info.dat informations
    When i go into the exercise with a ZOI question, the image disappeared.

Is there a commit not included into the 1.11.14 package ?

Thanks

Tanchon

**Comment by AngelFQC** [comment]
Ok. I tried with a full course backup.

**Comment by AngelFQC** [comment]
Hi @tanchon 

The hotspots questions are related to their images. These images are saved in the `document` course directory.
So when you create a backup for quizzes with this question type, you should import the image file related in the Documents block.

![imagen](https://user-images.githubusercontent.com/1697880/101068947-5f32cb00-3567-11eb-9c39-9ed13b961071.png)


I sent a commit with this warning message in the backup tool. And I added a new language variable in the translation system
```

$IfYourQuizHaveHotspotQuestionsIncludedYouShouldSelectTheImagesFromTheDocuments = "If your quiz have hotspot questions included, you should select the images related from the documents.";
```

**Comment by tanchon** [comment]
Hi @AngelFQC 

I tried this manipulation :

- from 11.chamilo.org => i made a partial backup of this course : [course test tanchon 1](https://11.chamilo.org/courses/COURSTANCHON/index.php). I selected one test ([Exercice Test GEA1 22/ 09](https://11.chamilo.org/main/exercise/admin.php?cidReq=COURSTANCHON&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=488)) and all images/quiz/...
- i opened another course on 11.chamilo.org ([tanchon 4](https://11.chamilo.org/courses/TANCHON4/index.php)).
- i tried to make an import of the zip file (i select "Documents ; All" and the exercise.


It works ! From a technical point of view, it's ok !

I make a suggestion => it is not very easy to chose the image during the import process. Their denomination isn't very clear. It is a problem when there are a lot of images :
![Capture100](https://user-images.githubusercontent.com/24507698/101153103-40ded500-3624-11eb-8cd8-e5cbc606634f.JPG)
May be the denomination of the image should be inspired from the denomination of the exercise it comes from ?

But it is another issue (i don't know if i have to open a new issue for that ?). I think this one can be closed.

Thanks !

**Comment by ywarnier** [comment]
@tanchon Please register another issue about the naming.
