### ISSUE TITLE
Error when trying to create a course in Hebrew

### ISSUE THREAD

**Issue by guymass** [chamilo/chamilo-lms#4670]
When ever I try to create a course with Hebrew title I get an error and it will not be created, however when I try in english I also get the same error but this time the course is created. Here are some screen shots:

although my interface is in Hebrew the field is for the course name and the button is for the create just for clarification:

A new test course in English:

![Screen Shot 5783-07-15 at 21 12 22](https://user-images.githubusercontent.com/58882903/230461547-58e82bb8-0552-43ce-bc4b-79b39527d387.jpg)
I get this error page:

![Screen Shot 5783-07-15 at 21 12 31](https://user-images.githubusercontent.com/58882903/230461650-9ec3a8e3-c8f1-494e-aea8-e1c0cf559399.jpg)
![Screen Shot 5783-07-15 at 21 12 53](https://user-images.githubusercontent.com/58882903/230461779-db6babf6-409d-4dbd-b67c-b344aa329338.jpg)

But on my courses page I see it just fine:
![Screen Shot 5783-07-15 at 21 13 52](https://user-images.githubusercontent.com/58882903/230461917-a4cf3268-e408-4215-ba2c-bb6e13926316.jpg)

On Hebrew I get the following and the course is not created or shown on my courses list:

![Screen Shot 5783-07-15 at 21 13 43](https://user-images.githubusercontent.com/58882903/230462179-d8c2df58-3b84-4561-ae80-4d94b58809c3.jpg)

It just says the course was not created. IMHO there is still not complete support with RTL languages and handeling Hebrew or Arabic languages.

I would like to be able to use it more in my language as much as possible so it would be greate if someone more knowledgeable can fix this problem. 

much thanks in advance :-)

**Comment by ywarnier** [comment]
Hi @guymass 
Let us check this. It's probably some very minor issue of escaping a quote in the JavaScript part of Chamilo (the defaults-he_HE.min.js it talks about). If so, we've already fixed similar issues for French and it's usually directly coming from some language string that has a quote where we're not expecting a quote.

**Comment by NicoDucou** [comment]
This commit fix the error when creating a course in hebrew. It does not block anymore on the folders creation in the document tool.
But there is still a problem when creating a course with a title with special caracters (for exemple with "לי האג'נדה שלי" as the title) then it blocks and does not create the course, nor gives a error message and just gets back to the list of course but with no course creation.

**Comment by ywarnier** [comment]
I'm considering this issue closed, with the negative effect that it doesn't filter special characters. We can work on that last issue in a later version, but hopefully this should not affect too many people.
