### ISSUE TITLE
[C2] Update BBB to use new database structure (videoconference tables)

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#6153]

**Comment by christianbeeznest** [comment]
This PR https://github.com/chamilo/chamilo-lms/issues/6153 migrates the BigBlueButton (BBB) plugin in Chamilo 2 to use the new videoconference database structure, replacing all direct SQL access (Database::select, insert, update, delete) with Doctrine-based repositories (ConferenceMeeting, ConferenceActivity, ConferenceRecording).

All data interactions now use Symfony and Doctrine ORM.

Note: This refactor requires thorough testing with a live BigBlueButton server to ensure meeting creation, joining, recording, and deletion are fully functional.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 

I've put a few comment on things to correct in your PR for it to work. I let you revise my comment and implement the proposed solution or a better one.
I also indicate here that on the listing.php page when clicking on the delete meeting icon it does not work, it is still present in the DB and there is no message on the interface indicating the success or the error.
It works when putting a meeting invisible or visible.
I did not check anything related to recording because I can not activate it.

**Comment by christianbeeznest** [comment]
> Hi [@christianbeeznest](https://github.com/christianbeeznest)
> 
> I've put a few comment on things to correct in your PR for it to work. I let you revise my comment and implement the proposed solution or a better one. I also indicate here that on the listing.php page when clicking on the delete meeting icon it does not work, it is still present in the DB and there is no message on the interface indicating the success or the error. It works when putting a meeting invisible or visible. I did not check anything related to recording because I can not activate it.

They are checked and fixed in the next commits of the same PR . 

Thanks for confirmation.

**Comment by NicoDucou** [comment]
I've tested again, and most of it works now.
I've put a new comment because there is still an error 500 when coming back from the visio.
The delete action is also still not working.

**Comment by christianbeeznest** [comment]
> I've tested again, and most of it works now. I've put a new comment because there is still an error 500 when coming back from the visio. The delete action is also still not working.

I just tested in ofajmigdev , delete action is working now, with the last changes.

Thanks for confirmation.

**Comment by NicoDucou** [comment]
I all seems to work fine with the general use of BBB meetings.
I did not test the recording because we need to be able to configure it and it depends on the general plugin installation system that is not ready yet to be able to access the configuration of the plugin.
I do not know if I close the issue and create a new one for that or if we leave this issue here until we test this part.
@ywarnier what do you think ?

**Comment by ywarnier** [comment]
You can close and create a new one as this one solves the database structure milestone we need for alpha

**Comment by ywarnier** [comment]
Closing. The only thing remaining is to test recordings, which we can do later on in the release milestones.
