### ISSUE TITLE
[C2] On a new installation the redirect to /main/install/index.php do not work

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#7224]
On a new installation if opening the root URL of the Chamilo it gives the following error instead of redirecting to /main/install/index.php : 

```
BadRequestHttpException
Show exception properties
Symfony\Component\HttpFoundation\Exception\
SessionNotFoundException
Session has not been set.

in /var/www/testing25.beeznest.com/www/vendor/symfony/http-foundation/Request.php (line 752)
Request->getSession()
in /var/www/testing25.beeznest.com/www/src/CoreBundle/EventListener/CidReqListener.php (line 214)
        if (!\is_array($controllerList)) {            return;        }        $request = $event->getRequest();        $sessionHandler = $request->getSession();        $courseId = (int) $request->get('cid');        // $groupId = (int) $request->get('gid');        // $sessionId = (int) $request->get('sid');
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelController (line 116)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 169)
in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 76)
in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/EventListener/ErrorListener.php -> handle (line 117)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelException (line 116)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 239)
in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleThrowable (line 132)
in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php -> terminateWithException (line 84)
in /var/www/testing25.beeznest.com/www/vendor/symfony/error-handler/ErrorHandler.php :: Symfony\Component\HttpKernel\EventListener\{closure} (line 538)
ErrorHandler->handleException()
Symfony\Component\HttpKernel\Exception\
BadRequestHttpException
Session has not been set.

in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php (line 83)
in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/EventListener/ErrorListener.php -> handle (line 117)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelException (line 116)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 239)
in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleThrowable (line 91)
in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/Kernel.php -> handle (line 197)
in /var/www/testing25.beeznest.com/www/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php -> handle (line 35)
in /var/www/testing25.beeznest.com/www/vendor/autoload_runtime.php -> run (line 29)
require_once('/var/www/testing25.beeznest.com/www/vendor/autoload_runtime.php')
in /var/www/testing25.beeznest.com/www/public/index.php (line 8)
/* For licensing terms, see /license.txt */use Chamilo\Kernel;use Symfony\Component\HttpFoundation\RedirectResponse as HttpRedirectResponse;require_once dirname(__DIR__).'/vendor/autoload_runtime.php';return function (array $context) {    // Chamilo    $isInstalled = $context['APP_INSTALLED'] ?? null;    if (1 !== (int) $isInstalled) {
Symfony\Component\HttpFoundation\Exception\
SessionNotFoundException
Session has not been set.

in [/var/www/testing25.beeznest.com/www/vendor/symfony/http-foundation/Request.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/http-foundation/Request.php#L752)(line 752)
Request->getSession()
in [/var/www/testing25.beeznest.com/www/src/CoreBundle/EventListener/CidReqListener.php ](file:///var/www/testing25.beeznest.com/www/src/CoreBundle/EventListener/CidReqListener.php#L214)(line 214)
        if (!\is_array($controllerList)) {            return;        }        $request = $event->getRequest();        $sessionHandler = $request->getSession();        $courseId = (int) $request->get('cid');        // $groupId = (int) $request->get('gid');        // $sessionId = (int) $request->get('sid');
in [/var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php#L116)-> onKernelController (line 116)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php#L220)-> __invoke (line 220)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php#L56)-> callListeners (line 56)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php#L139)-> dispatch (line 139)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php#L169)-> dispatch (line 169)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php#L76)-> handleRaw (line 76)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/EventListener/ErrorListener.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/EventListener/ErrorListener.php#L117)-> handle (line 117)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php#L116)-> onKernelException (line 116)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php#L220)-> __invoke (line 220)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php#L56)-> callListeners (line 56)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php#L139)-> dispatch (line 139)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php#L239)-> dispatch (line 239)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php#L132)-> handleThrowable (line 91)
in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/Kernel.php -> handle (line 197)
in /var/www/testing25.beeznest.com/www/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php -> handle (line 35)
in /var/www/testing25.beeznest.com/www/vendor/autoload_runtime.php -> run (line 29)
require_once('/var/www/testing25.beeznest.com/www/vendor/autoload_runtime.php')
in /var/www/testing25.beeznest.com/www/public/index.php (line 8)
Doctrine\DBAL\Exception\
TableNotFoundException
An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing25.access_url' doesn't exist

in /var/www/testing25.beeznest.com/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php (line 51)
in /var/www/testing25.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> convert (line 1976)
in /var/www/testing25.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> handleDriverException (line 1918)
in /var/www/testing25.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> convertExceptionDuringQuery (line 1111)
in /var/www/testing25.beeznest.com/www/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php -> executeQuery (line 909)
in /var/www/testing25.beeznest.com/www/vendor/doctrine/orm/src/EntityRepository.php -> count (line 254)
EntityRepository->count()
in /var/www/testing25.beeznest.com/www/src/CoreBundle/Helpers/AccessUrlHelper.php (line 30)
    public function isMultiple(): bool    {        static $accessUrlEnabled;        if (!isset($accessUrlEnabled)) {            $accessUrlEnabled = $this->accessUrlRepository->count([]) > 1;        }        return $accessUrlEnabled;    }
AccessUrlHelper->isMultiple()
in /var/www/testing25.beeznest.com/www/src/CoreBundle/EventListener/AccessUrlValidationListener.php (line 58)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelRequest (line 116)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php#L83)-> dispatch (line 157)
in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 76)
in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/Kernel.php -> handle (line 197)
in /var/www/testing25.beeznest.com/www/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php -> handle (line 35)
in /var/www/testing25.beeznest.com/www/vendor/autoload_runtime.php -> run (line 29)
require_once('/var/www/testing25.beeznest.com/www/vendor/autoload_runtime.php')
in /var/www/testing25.beeznest.com/www/public/index.php (line 8)
Doctrine\DBAL\Driver\PDO\
Exception
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing25.access_url' doesn't exist

in /var/www/testing25.beeznest.com/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php (line 24)
in /var/www/testing25.beeznest.com/www/vendor/doctrine/dbal/src/Driver/PDO/Connection.php :: new (line 76)
in /var/www/testing25.beeznest.com/www/vendor/doctrine/dbal/src/Driver/Middleware/AbstractConnectionMiddleware.php -> query (line 33)
in /var/www/testing25.beeznest.com/www/vendor/doctrine/dbal/src/Logging/Connection.php -> query (line 43)
in /var/www/testing25.beeznest.com/www/vendor/doctrine/dbal/src/Driver/Middleware/AbstractConnectionMiddleware.php -> query (line 33)
in /var/www/testing25.beeznest.com/www/vendor/symfony/doctrine-bridge/Middleware/Debug/DBAL3/Connection.php -> query (line 58)
in /var/www/testing25.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> query (line 1106)
in /var/www/testing25.beeznest.com/www/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php -> executeQuery (line 909)
in /var/www/testing25.beeznest.com/www/vendor/doctrine/orm/src/EntityRepository.php -> count (line 254)
EntityRepository->count()
in /var/www/testing25.beeznest.com/www/src/CoreBundle/Helpers/AccessUrlHelper.php (line 30)
    public function isMultiple(): bool    {        static $accessUrlEnabled;        if (!isset($accessUrlEnabled)) {            $accessUrlEnabled = $this->accessUrlRepository->count([]) > 1;        }        return $accessUrlEnabled;    }
AccessUrlHelper->isMultiple()
in /var/www/testing25.beeznest.com/www/src/CoreBundle/EventListener/AccessUrlValidationListener.php (line 58)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php#L116)-> onKernelRequest (line 116)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php#L220)-> __invoke (line 220)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php#L56)-> callListeners (line 56)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php#L139)-> dispatch (line 139)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php#L239)-> dispatch (line 157)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php#L91)-> handleRaw (line 76)
in /var/www/testing25.beeznest.com/www/vendor/symfony/http-kernel/Kernel.php -> handle (line 197)
in [/var/www/testing25.beeznest.com/www/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php ](file:///var/www/testing25.beeznest.com/www/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php#L35)-> handle (line 35)
in [/var/www/testing25.beeznest.com/www/vendor/autoload_runtime.php ](file:///var/www/testing25.beeznest.com/www/vendor/autoload_runtime.php#L29)-> run (line 29)
require_once('/var/www/testing25.beeznest.com/www/vendor/autoload_runtime.php')
in [/var/www/testing25.beeznest.com/www/public/index.php ](file:///var/www/testing25.beeznest.com/www/public/index.php#L8)(line 8)
```

**Comment by NicoDucou** [comment]
This problem only occurs if there is a .env file already present from a previous installation.

**Comment by christianbeeznest** [comment]
It is ckecked with this PR https://github.com/chamilo/chamilo-lms/pull/7330

Fixed the redirect on fresh installations by preventing install-time crashes when the session is not initialized and the database tables are not created yet. Added safe guards to avoid calling Request->getSession() when no session exists, and made AccessUrl detection resilient (catching DB/table-not-found cases) so the root URL can correctly redirect to /main/install/index.php even if an old .env is present.

**Comment by NicoDucou** [comment]
I tried with your branch but I still have GH-7274 but I still have this error :

```
An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing23.access_url' doesn't exist
￼Exceptions 9
￼Stack Traces 9
Doctrine\DBAL\Exception\
TableNotFoundException
Show exception properties
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php (line 51)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> convert (line 1976)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> handleDriverException (line 1918)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> convertExceptionDuringQuery (line 1111)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php -> executeQuery (line 779)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/EntityRepository.php -> load (line 240)
EntityRepository->findOneBy()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 1488)
                'http://'.$host.'/',                'http://'.$host,            ]));            foreach ($candidates as $candidate) {                $found = $repo->findOneBy(['url' => $candidate]);                if ($found instanceof AccessUrl) {                    $this->url = $found;                    return;                }
SettingsManager->ensureUrlResolved()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 173)
SettingsManager->getSetting()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 61)
LocaleSubscriber->getCurrentLanguage()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 50)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelRequest (line 116)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 157)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 76)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/EventListener/ErrorListener.php -> handle (line 117)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelException (line 116)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 239)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleThrowable (line 132)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php -> terminateWithException (line 84)
in /var/www/testing23.beeznest.com/www/vendor/symfony/error-handler/ErrorHandler.php :: Symfony\Component\HttpKernel\EventListener\{closure} (line 538)
ErrorHandler->handleException()
Doctrine\DBAL\Driver\PDO\
Exception
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing23.access_url' doesn't exist

in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php (line 24)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/PDO/Statement.php :: new (line 132)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php -> execute (line 69)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Logging/Statement.php -> execute (line 98)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php -> execute (line 69)
in /var/www/testing23.beeznest.com/www/vendor/symfony/doctrine-bridge/Middleware/Debug/DBAL3/Statement.php -> execute (line 70)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> execute (line 1104)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php -> executeQuery (line 779)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/EntityRepository.php -> load (line 240)
EntityRepository->findOneBy()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 1488)
                'http://'.$host.'/',                'http://'.$host,            ]));            foreach ($candidates as $candidate) {                $found = $repo->findOneBy(['url' => $candidate]);                if ($found instanceof AccessUrl) {                    $this->url = $found;                    return;                }
SettingsManager->ensureUrlResolved()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 173)
SettingsManager->getSetting()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 61)
LocaleSubscriber->getCurrentLanguage()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 50)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelRequest (line 116)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 157)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 76)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/EventListener/ErrorListener.php -> handle (line 117)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelException (line 116)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 239)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleThrowable (line 132)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php -> terminateWithException (line 84)
in /var/www/testing23.beeznest.com/www/vendor/symfony/error-handler/ErrorHandler.php :: Symfony\Component\HttpKernel\EventListener\{closure} (line 538)
ErrorHandler->handleException()
PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing23.access_url' doesn't exist

in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/PDO/Statement.php (line 130)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/PDO/Statement.php -> execute (line 130)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php -> execute (line 69)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Logging/Statement.php -> execute (line 98)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php -> execute (line 69)
in /var/www/testing23.beeznest.com/www/vendor/symfony/doctrine-bridge/Middleware/Debug/DBAL3/Statement.php -> execute (line 70)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> execute (line 1104)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php -> executeQuery (line 779)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/EntityRepository.php -> load (line 240)
EntityRepository->findOneBy()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 1488)
                'http://'.$host.'/',                'http://'.$host,            ]));            foreach ($candidates as $candidate) {                $found = $repo->findOneBy(['url' => $candidate]);                if ($found instanceof AccessUrl) {                    $this->url = $found;                    return;                }
SettingsManager->ensureUrlResolved()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 173)
SettingsManager->getSetting()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 61)
LocaleSubscriber->getCurrentLanguage()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 50)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelRequest (line 116)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 157)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 76)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/EventListener/ErrorListener.php -> handle (line 117)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelException (line 116)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 239)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleThrowable (line 132)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/EventListener/DebugHandlersListener.php -> terminateWithException (line 84)
in /var/www/testing23.beeznest.com/www/vendor/symfony/error-handler/ErrorHandler.php :: Symfony\Component\HttpKernel\EventListener\{closure} (line 538)
ErrorHandler->handleException()
Doctrine\DBAL\Exception\
TableNotFoundException
An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing23.access_url' doesn't exist

in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php (line 51)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> convert (line 1976)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> handleDriverException (line 1918)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> convertExceptionDuringQuery (line 1111)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php -> executeQuery (line 779)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/EntityRepository.php -> load (line 240)
EntityRepository->findOneBy()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 1488)
                'http://'.$host.'/',                'http://'.$host,            ]));            foreach ($candidates as $candidate) {                $found = $repo->findOneBy(['url' => $candidate]);                if ($found instanceof AccessUrl) {                    $this->url = $found;                    return;                }
SettingsManager->ensureUrlResolved()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 173)
SettingsManager->getSetting()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 61)
LocaleSubscriber->getCurrentLanguage()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 50)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelRequest (line 116)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 157)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 76)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/EventListener/ErrorListener.php -> handle (line 117)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelException (line 116)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 239)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleThrowable (line 91)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/Kernel.php -> handle (line 197)
in /var/www/testing23.beeznest.com/www/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php -> handle (line 35)
in /var/www/testing23.beeznest.com/www/vendor/autoload_runtime.php -> run (line 29)
require_once('/var/www/testing23.beeznest.com/www/vendor/autoload_runtime.php')
in /var/www/testing23.beeznest.com/www/public/index.php (line 8)
Doctrine\DBAL\Driver\PDO\
Exception
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing23.access_url' doesn't exist

in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php (line 24)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/PDO/Statement.php :: new (line 132)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php -> execute (line 69)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Logging/Statement.php -> execute (line 98)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php -> execute (line 69)
in /var/www/testing23.beeznest.com/www/vendor/symfony/doctrine-bridge/Middleware/Debug/DBAL3/Statement.php -> execute (line 70)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> execute (line 1104)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php -> executeQuery (line 779)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/EntityRepository.php -> load (line 240)
EntityRepository->findOneBy()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 1488)
                'http://'.$host.'/',                'http://'.$host,            ]));            foreach ($candidates as $candidate) {                $found = $repo->findOneBy(['url' => $candidate]);                if ($found instanceof AccessUrl) {                    $this->url = $found;                    return;                }
SettingsManager->ensureUrlResolved()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 173)
SettingsManager->getSetting()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 61)
LocaleSubscriber->getCurrentLanguage()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 50)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelRequest (line 116)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 157)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 76)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/EventListener/ErrorListener.php -> handle (line 117)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelException (line 116)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 239)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleThrowable (line 91)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/Kernel.php -> handle (line 197)
in /var/www/testing23.beeznest.com/www/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php -> handle (line 35)
in /var/www/testing23.beeznest.com/www/vendor/autoload_runtime.php -> run (line 29)
require_once('/var/www/testing23.beeznest.com/www/vendor/autoload_runtime.php')
in /var/www/testing23.beeznest.com/www/public/index.php (line 8)
PDOException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing23.access_url' doesn't exist

in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/PDO/Statement.php (line 130)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/PDO/Statement.php -> execute (line 130)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php -> execute (line 69)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Logging/Statement.php -> execute (line 98)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php -> execute (line 69)
in /var/www/testing23.beeznest.com/www/vendor/symfony/doctrine-bridge/Middleware/Debug/DBAL3/Statement.php -> execute (line 70)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> execute (line 1104)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php -> executeQuery (line 779)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/EntityRepository.php -> load (line 240)
EntityRepository->findOneBy()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 1488)
                'http://'.$host.'/',                'http://'.$host,            ]));            foreach ($candidates as $candidate) {                $found = $repo->findOneBy(['url' => $candidate]);                if ($found instanceof AccessUrl) {                    $this->url = $found;                    return;                }
SettingsManager->ensureUrlResolved()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 173)
SettingsManager->getSetting()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 61)
LocaleSubscriber->getCurrentLanguage()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 50)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelRequest (line 116)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 157)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 76)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/EventListener/ErrorListener.php -> handle (line 117)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelException (line 116)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 239)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleThrowable (line 91)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/Kernel.php -> handle (line 197)
in /var/www/testing23.beeznest.com/www/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php -> handle (line 35)
in /var/www/testing23.beeznest.com/www/vendor/autoload_runtime.php -> run (line 29)
require_once('/var/www/testing23.beeznest.com/www/vendor/autoload_runtime.php')
in /var/www/testing23.beeznest.com/www/public/index.php (line 8)
Doctrine\DBAL\Exception\
TableNotFoundException
An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing23.access_url' doesn't exist

in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php (line 51)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> convert (line 1976)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> handleDriverException (line 1918)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> convertExceptionDuringQuery (line 1111)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php -> executeQuery (line 779)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/EntityRepository.php -> load (line 240)
EntityRepository->findOneBy()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 1488)
                'http://'.$host.'/',                'http://'.$host,            ]));            foreach ($candidates as $candidate) {                $found = $repo->findOneBy(['url' => $candidate]);                if ($found instanceof AccessUrl) {                    $this->url = $found;                    return;                }
SettingsManager->ensureUrlResolved()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 173)
SettingsManager->getSetting()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 61)
LocaleSubscriber->getCurrentLanguage()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 50)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelRequest (line 116)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 157)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 76)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/Kernel.php -> handle (line 197)
in /var/www/testing23.beeznest.com/www/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php -> handle (line 35)
in /var/www/testing23.beeznest.com/www/vendor/autoload_runtime.php -> run (line 29)
require_once('/var/www/testing23.beeznest.com/www/vendor/autoload_runtime.php')
in /var/www/testing23.beeznest.com/www/public/index.php (line 8)
Doctrine\DBAL\Driver\PDO\
Exception
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing23.access_url' doesn't exist

in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/PDO/Exception.php (line 24)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/PDO/Statement.php :: new (line 132)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php -> execute (line 69)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Logging/Statement.php -> execute (line 98)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Driver/Middleware/AbstractStatementMiddleware.php -> execute (line 69)
in /var/www/testing23.beeznest.com/www/vendor/symfony/doctrine-bridge/Middleware/Debug/DBAL3/Statement.php -> execute (line 70)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/dbal/src/Connection.php -> execute (line 1104)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/Persisters/Entity/BasicEntityPersister.php -> executeQuery (line 779)
in /var/www/testing23.beeznest.com/www/vendor/doctrine/orm/src/EntityRepository.php -> load (line 240)
EntityRepository->findOneBy()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 1488)
                'http://'.$host.'/',                'http://'.$host,            ]));            foreach ($candidates as $candidate) {                $found = $repo->findOneBy(['url' => $candidate]);                if ($found instanceof AccessUrl) {                    $this->url = $found;                    return;                }
SettingsManager->ensureUrlResolved()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/Settings/SettingsManager.php (line 173)
SettingsManager->getSetting()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 61)
LocaleSubscriber->getCurrentLanguage()
in /var/www/testing23.beeznest.com/www/src/CoreBundle/EventSubscriber/LocaleSubscriber.php (line 50)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/WrappedListener.php -> onKernelRequest (line 116)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> __invoke (line 220)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/EventDispatcher.php -> callListeners (line 56)
in /var/www/testing23.beeznest.com/www/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 139)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> dispatch (line 157)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/HttpKernel.php -> handleRaw (line 76)
in /var/www/testing23.beeznest.com/www/vendor/symfony/http-kernel/Kernel.php -> handle (line 197)
in /var/www/testing23.beeznest.com/www/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php -> handle (line 35)
in /var/www/testing23.beeznest.com/www/vendor/autoload_runtime.php -> run (line 29)
require_once('/var/www/testing23.beeznest.com/www/vendor/autoload_runtime.php')
in /var/www/testing23.beeznest.com/www/public/index.php (line 8)

```

**Comment by christianbeeznest** [comment]
> I tried with your branch but I still have [GH-7274](https://github.com/chamilo/chamilo-lms/issues/7274) but I still have this error :
> 
> ```
> An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testing23.access_url' doesn't exist
> ...
> ```

It is checked and improved with this commit https://github.com/chamilo/chamilo-lms/pull/7330/commits/226f9116becfa8fa81b734188ca234830d148147

Implemented safer install/update detection to prevent false “update available” states when .env has APP_INSTALLED=1 but the database is missing, empty, or credentials are wrong. The installer now checks that the DB is reachable and actually looks initialized (presence of settings / settings_current with at least one row) before offering migration, and reads chamilo_database_version to decide whether an update is needed. If the DB is not initialized or not reachable, the install wizard remains available for a fresh install.

Thanks for confirmation.

**Comment by NicoDucou** [comment]
All good now. I've accepted the PR and close this task now
